from __future__ import absolute_import
from __future__ import unicode_literals

from django.db import models

class JobApplication(models.Model):
    # id = models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)
    job_number = models.AutoField(verbose_name='Job_Number', serialize=False, auto_created=True, primary_key=True)
    bin = models.IntegerField(null=False, blank=False)
    job_type = models.CharField(null=True, blank=True, max_length=200)
    doc_number = models.CharField(null=True, blank=True, max_length=200)
    city_owned = models.CharField(null=True, blank=True, max_length=200)
    filed_type = models.CharField(null=True, blank=True, max_length=200)
    plumbing = models.CharField(null=True, blank=True, max_length=200)
    mechanical = models.CharField(null=True, blank=True, max_length=200)
    boiler = models.CharField(null=True, blank=True, max_length=200)
    fuel_burning = models.CharField(null=True, blank=True, max_length=200)
    fuel_Storage = models.CharField(null=True, blank=True, max_length=200)
    equipment = models.CharField(null=True, blank=True, max_length=200)
    other_work_type = models.CharField(null=True, blank=True, max_length=200)
    other_work_type_desc = models.CharField(null=True, blank=True, max_length=200)
    pre_filing_date = models.CharField(null=True, blank=True, max_length=200)
    approved = models.CharField(null=True, blank=True, max_length=200)
    fully_permitted = models.CharField(null=True, blank=True, max_length=200)
    initial_cost = models.CharField(null=True, blank=True, max_length=200)
    existing_zoning_sqft = models.CharField(null=True, blank=True, max_length=200)
    proposed_zoning_sqft = models.CharField(null=True, blank=True, max_length=200)
    enlargement_sq_footage = models.CharField(null=True, blank=True, max_length=200)
    street_frontage = models.CharField(null=True, blank=True, max_length=200)
    current_num_floors = models.IntegerField(null=True, blank=True)
    proposed_num_floors = models.IntegerField(null=True, blank=True)
    current_height = models.IntegerField(null=True, blank=True)
    proposed_height = models.IntegerField(null=True, blank=True)
    proposed_dwelling_units = models.IntegerField(null=True, blank=True)
    current_occupancy = models.IntegerField(null=True, blank=True)
    proposed_occupancy = models.IntegerField(null=True, blank=True)
    total_construction_floor_area = models.IntegerField(null=True, blank=True)
    signoff_date = models.DateField(null=True)
    building_class = models.CharField(null=True, blank=True, max_length=200)